# This workflow will build a package using Maven and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java/blob/main/docs/advanced-usage.md#apache-maven-with-a-settings-path

name: Manual Maven Package

on:
  workflow_dispatch:
    inputs:
      Keycloak-Version:
        required: true
      KC2FA-Version:
        required: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ inputs.KC2FA-Version }}
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: maven
      - name: Set version
        run: mvn versions:set -DnewVersion=${{ inputs.KC2FA-Version }}-KC${{ inputs.Keycloak-Version }}
      - name: Build with Maven
        run: mvn -Dkeycloak.version=${{ inputs.Keycloak-Version }} -B package --file pom.xml
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: target/keycloak-2fa-email-authenticator*
          name: Keycloak 2FA Email Authenticator v${{ inputs.KC2FA-Version }}
          tag_name: ${{ inputs.KC2FA-Version }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
